development:
  adapter: postgresql
  encoding: unicode
  database: vegan_development
  pool: 5
  host: localhost
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: vegan_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  host: localhost
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
